##
# This file contains some overrides that are useful for local development
# and Kalabox
#

api:
  # Comment this and uncomment 'build' below if you want to edit your
  # local dockerfile and build from there. This is useful for development
  image: viperks/api:latest

  # Uncomment this and comment 'image' above if you want to edit your
  # local dockerfile and build from there. This is useful for development
  #
  #build: ./dockerfiles/api
  volumes:
    - $KALABOX_APP_ROOT_BIND:/src
  entrypoint: /src/local/scripts/php-fpm.sh
  command: -d xdebug.remote_host=$KALABOX_ENGINE_REMOTE_IP
  environment:
    KALABOX_GID: $KALABOX_ENGINE_GID
    KALABOX_UID: $KALABOX_ENGINE_ID
    TERM: xterm
web:
  # Comment this and uncomment 'build' below if you want to edit your
  # local dockerfile and build from there. This is useful for development
  image: viperks/web:api-latest

  # Uncomment this and comment 'image' above if you want to edit your
  # local dockerfile and build from there. This is useful for development
  #
  #build: ./dockerfiles/web
  volumes:
    - $KALABOX_APP_ROOT_BIND:/src
  entrypoint: /src/local/scripts/nginx.sh
  command: -g "daemon off;"
  environment:
    KALABOX_GID: $KALABOX_ENGINE_GID
    KALABOX_UID: $KALABOX_ENGINE_ID
    TERM: xterm
